[etcd]
Host = "ETCD_HOST:2379"

[pillx]
GatewayOuterHost = "127.0.0.1"
GatewayOuterPort = 9127
GatewayInnerHost = "127.0.0.1"
GatewayInnerPort = 10086
WorkerInnerHost = "127.0.0.1"
WorkerInnerPort = 18600
GatewayName     = "testgateway"
WorkerName      = "testworker"

[redis0]
Host = "REDIS_HOST"
Port = 6380
User = "dev"
Password = "123456"
