// Code generated by protoc-gen-go.
// source: Pill.proto
// DO NOT EDIT!

/*
Package Proto is a generated protocol buffer package.

It is generated from these files:
	Pill.proto

It has these top-level messages:
	ChatHeader
	ChatData
	ChatList
	BlockData
	WorkerHandShark
	MessageData
	HandShake
*/
package Proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ChatHeader struct {
	// optional int32 RoomId   = 1;
	// optional int32 Type   = 2;
	// optional int32 Status   = 3;
	// optional int32 Cmd   = 4;
	// optional int32 Sid   = 5;
	// 正常消息为1，返回消息非1
	Code             *int32  `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Msg              *string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatHeader) Reset()                    { *m = ChatHeader{} }
func (m *ChatHeader) String() string            { return proto.CompactTextString(m) }
func (*ChatHeader) ProtoMessage()               {}
func (*ChatHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatHeader) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ChatHeader) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type ChatData struct {
	Header           *ChatHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Msg              *string     `protobuf:"bytes,3,opt,name=Msg" json:"Msg,omitempty"`
	Msgjson          *string     `protobuf:"bytes,4,opt,name=Msgjson" json:"Msgjson,omitempty"`
	Uid              *int32      `protobuf:"varint,5,opt,name=Uid" json:"Uid,omitempty"`
	Uname            *string     `protobuf:"bytes,6,opt,name=Uname" json:"Uname,omitempty"`
	Upic             *string     `protobuf:"bytes,7,opt,name=Upic" json:"Upic,omitempty"`
	Utitle           *string     `protobuf:"bytes,8,opt,name=Utitle" json:"Utitle,omitempty"`
	Img              *string     `protobuf:"bytes,9,opt,name=Img" json:"Img,omitempty"`
	Timestamp        *int32      `protobuf:"varint,10,opt,name=Timestamp" json:"Timestamp,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatData) Reset()                    { *m = ChatData{} }
func (m *ChatData) String() string            { return proto.CompactTextString(m) }
func (*ChatData) ProtoMessage()               {}
func (*ChatData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatData) GetHeader() *ChatHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ChatData) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *ChatData) GetMsgjson() string {
	if m != nil && m.Msgjson != nil {
		return *m.Msgjson
	}
	return ""
}

func (m *ChatData) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *ChatData) GetUname() string {
	if m != nil && m.Uname != nil {
		return *m.Uname
	}
	return ""
}

func (m *ChatData) GetUpic() string {
	if m != nil && m.Upic != nil {
		return *m.Upic
	}
	return ""
}

func (m *ChatData) GetUtitle() string {
	if m != nil && m.Utitle != nil {
		return *m.Utitle
	}
	return ""
}

func (m *ChatData) GetImg() string {
	if m != nil && m.Img != nil {
		return *m.Img
	}
	return ""
}

func (m *ChatData) GetTimestamp() int32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ChatList struct {
	ChatItem         []*ChatData `protobuf:"bytes,1,rep,name=ChatItem" json:"ChatItem,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatList) Reset()                    { *m = ChatList{} }
func (m *ChatList) String() string            { return proto.CompactTextString(m) }
func (*ChatList) ProtoMessage()               {}
func (*ChatList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChatList) GetChatItem() []*ChatData {
	if m != nil {
		return m.ChatItem
	}
	return nil
}

type BlockData struct {
	Header           *ChatHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	BlockUid         *int32      `protobuf:"varint,2,opt,name=BlockUid" json:"BlockUid,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *BlockData) Reset()                    { *m = BlockData{} }
func (m *BlockData) String() string            { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()               {}
func (*BlockData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BlockData) GetHeader() *ChatHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BlockData) GetBlockUid() int32 {
	if m != nil && m.BlockUid != nil {
		return *m.BlockUid
	}
	return 0
}

type WorkerHandShark struct {
	IP               *string `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Uid              *int32  `protobuf:"varint,3,opt,name=Uid" json:"Uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WorkerHandShark) Reset()                    { *m = WorkerHandShark{} }
func (m *WorkerHandShark) String() string            { return proto.CompactTextString(m) }
func (*WorkerHandShark) ProtoMessage()               {}
func (*WorkerHandShark) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WorkerHandShark) GetIP() string {
	if m != nil && m.IP != nil {
		return *m.IP
	}
	return ""
}

func (m *WorkerHandShark) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *WorkerHandShark) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type MessageData struct {
	Header           *ChatHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MessageData) Reset()                    { *m = MessageData{} }
func (m *MessageData) String() string            { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()               {}
func (*MessageData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MessageData) GetHeader() *ChatHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type HandShake struct {
	Header           *ChatHeader `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Timestamp        *int32      `protobuf:"varint,2,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Token            *uint32     `protobuf:"varint,3,opt,name=Token" json:"Token,omitempty"`
	RoomId           *int32      `protobuf:"varint,4,opt,name=RoomId" json:"RoomId,omitempty"`
	ConnectId        *int32      `protobuf:"varint,5,opt,name=ConnectId" json:"ConnectId,omitempty"`
	Uid              *int32      `protobuf:"varint,6,opt,name=Uid" json:"Uid,omitempty"`
	Platform         *int32      `protobuf:"varint,7,opt,name=Platform" json:"Platform,omitempty"`
	Uname            *string     `protobuf:"bytes,8,opt,name=Uname" json:"Uname,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *HandShake) Reset()                    { *m = HandShake{} }
func (m *HandShake) String() string            { return proto.CompactTextString(m) }
func (*HandShake) ProtoMessage()               {}
func (*HandShake) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *HandShake) GetHeader() *ChatHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HandShake) GetTimestamp() int32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *HandShake) GetToken() uint32 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func (m *HandShake) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *HandShake) GetConnectId() int32 {
	if m != nil && m.ConnectId != nil {
		return *m.ConnectId
	}
	return 0
}

func (m *HandShake) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *HandShake) GetPlatform() int32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *HandShake) GetUname() string {
	if m != nil && m.Uname != nil {
		return *m.Uname
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatHeader)(nil), "Proto.ChatHeader")
	proto.RegisterType((*ChatData)(nil), "Proto.ChatData")
	proto.RegisterType((*ChatList)(nil), "Proto.ChatList")
	proto.RegisterType((*BlockData)(nil), "Proto.BlockData")
	proto.RegisterType((*WorkerHandShark)(nil), "Proto.WorkerHandShark")
	proto.RegisterType((*MessageData)(nil), "Proto.MessageData")
	proto.RegisterType((*HandShake)(nil), "Proto.HandShake")
}

var fileDescriptor0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6b, 0xe3, 0x30,
	0x10, 0xc5, 0x76, 0xec, 0xd8, 0x13, 0x76, 0xb3, 0x2b, 0x96, 0x45, 0x2c, 0x7b, 0x28, 0x3e, 0xb5,
	0x14, 0x72, 0xc8, 0xa5, 0x3d, 0x37, 0x85, 0xc6, 0xd0, 0x14, 0xa3, 0xc6, 0xf4, 0x2c, 0x62, 0x35,
	0x71, 0xfd, 0xa1, 0x60, 0xeb, 0x27, 0xb7, 0xff, 0xa3, 0xd2, 0xf8, 0x2b, 0xed, 0x2d, 0x27, 0xbd,
	0x37, 0x68, 0x9e, 0xe6, 0x3d, 0x0d, 0x40, 0x9c, 0x15, 0xc5, 0xe2, 0x58, 0x4b, 0x25, 0x89, 0x1b,
	0x9b, 0x23, 0x5c, 0x02, 0xac, 0x0e, 0x5c, 0xad, 0x05, 0x4f, 0x45, 0x4d, 0x08, 0x4c, 0x56, 0x32,
	0x15, 0xd4, 0xba, 0xb0, 0x2e, 0x5d, 0x86, 0x98, 0xfc, 0x02, 0x67, 0xd3, 0xec, 0xa9, 0xad, 0x4b,
	0x01, 0x33, 0x30, 0xfc, 0xb0, 0xc0, 0x37, 0x4d, 0xf7, 0x5c, 0x71, 0x72, 0x05, 0x5e, 0xdb, 0x8c,
	0x4d, 0xb3, 0xe5, 0xef, 0x05, 0x0a, 0x2f, 0x46, 0x55, 0xd6, 0x5d, 0xe8, 0x95, 0x9c, 0x41, 0x89,
	0x50, 0x98, 0xea, 0xe3, 0xad, 0x91, 0x15, 0x9d, 0x60, 0xb5, 0xa7, 0xe6, 0x6e, 0x92, 0xa5, 0xd4,
	0xc5, 0x41, 0x0c, 0x24, 0x7f, 0xc0, 0x4d, 0x2a, 0x5e, 0x0a, 0xea, 0xe1, 0xcd, 0x96, 0x98, 0x89,
	0x93, 0x63, 0xb6, 0xa3, 0x53, 0x2c, 0x22, 0x26, 0x7f, 0xc1, 0x4b, 0x54, 0xa6, 0x0a, 0x41, 0x7d,
	0xac, 0x76, 0xcc, 0x68, 0x46, 0xe5, 0x9e, 0x06, 0xed, 0xfb, 0x1a, 0x92, 0xff, 0x10, 0x6c, 0xb3,
	0x52, 0x34, 0x8a, 0x97, 0x47, 0x0a, 0xf8, 0xd6, 0x58, 0x08, 0x6f, 0x5a, 0x9b, 0x8f, 0x59, 0xa3,
	0xc8, 0x75, 0x8b, 0x23, 0x25, 0x4a, 0x6d, 0xd4, 0xd1, 0x46, 0xe7, 0x27, 0x46, 0x4d, 0x12, 0x6c,
	0xb8, 0x10, 0x32, 0x08, 0xee, 0x0a, 0xb9, 0xcb, 0xcf, 0x0d, 0xe8, 0x1f, 0xf8, 0xd8, 0x67, 0x9c,
	0xdb, 0x38, 0xcd, 0xc0, 0xc3, 0x07, 0x98, 0xbf, 0xc8, 0x3a, 0x17, 0xf5, 0x9a, 0x57, 0xe9, 0xf3,
	0x81, 0xd7, 0x39, 0xf9, 0x09, 0x76, 0x14, 0xa3, 0x6a, 0xc0, 0x34, 0x32, 0x59, 0x3c, 0x99, 0x80,
	0xda, 0xaf, 0x42, 0xdc, 0xe7, 0xe8, 0x0c, 0x39, 0x86, 0xb7, 0x30, 0xdb, 0x88, 0xa6, 0xe1, 0x7b,
	0x71, 0xe6, 0x78, 0xe1, 0xbb, 0x05, 0x41, 0xf7, 0x7a, 0x2e, 0xce, 0xf1, 0xf5, 0x25, 0x66, 0xfb,
	0x5b, 0xcc, 0xe6, 0x63, 0xb7, 0x32, 0x17, 0x15, 0x0e, 0xf9, 0x83, 0xb5, 0xc4, 0x7c, 0x22, 0x93,
	0xb2, 0x8c, 0x52, 0xdc, 0x0c, 0x97, 0x75, 0xcc, 0x68, 0xad, 0x64, 0x55, 0x89, 0x9d, 0x8a, 0xfa,
	0xf5, 0x18, 0x0b, 0xbd, 0x5d, 0x6f, 0x5c, 0x1b, 0x9d, 0x69, 0x5c, 0x70, 0xf5, 0x2a, 0xeb, 0x12,
	0x97, 0x44, 0x67, 0xda, 0xf3, 0x71, 0xa5, 0xfc, 0x93, 0x95, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0xab, 0xae, 0x7a, 0x2b, 0x26, 0x03, 0x00, 0x00,
}
